function L = generate_sequence(A, T)
% Inputs: NxN transition matrix A (row stochastic), and number of steps T
%
% Output: Sequence L (length T) of nodes generated by Markov chain with 
% transitions defined by A

N = size(A,1);

L = zeros(1, 2*T);
L(1) = randi(N);

% Loop over twice the total length of walk that we want:
for t = 2:(2*T)
    
    L(t) = randsample(N, 1, true, A(L(t-1),:));

end

% Only keep the final T nodes. The purpose of this is to let the walk "burn
% in" in case the stationary distribution is not uniform:
L = L((T+1):end);